title: template title should be replace
voting_method: secret_ballot
starting_method: scheduled
starting_picker: 06/07/2025 7:00 AM
starting: 2025-06-07T07:00:00+02:00
ending_method: scheduled
ending_picker: 06/08/2025 8:00 PM
ending: 2025-06-08T20:00:00+02:00
locale: fr
tally_method: automatic
